# Welcome to vaporwave

title: 3D삽질
description: >- # this means to ignore newlines until "baseurl:"
  비정기 취미 프로젝트 가동중

url: https://hyunjun529.github.io # the base hostname & protocol for your site, e.g. http://example.com\
baseurl: "" # the subpath of your site, e.g. /blog
production_url: https://hyunjun529.github.io
favicon: "favicon.ico"

# Jekyll
encoding: "utf-8"
markdown: kramdown
sass:
  sass_dir: _sass
plugins:
  - jekyll-feed

# Comment
disqus:
  enable: true
  shortname: blog-p316-net
utterances:
  enable: true

# ETC
email: hyunjun529@gmail.com
twitter_username: zaq1qaz
github_username:  hyunjun529
google_analytics: UA-55359566-9

# vaporwave
vaporwave:
  search: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Not Defaults

